volumes:
  db-data:

services:
  backend:
    build:
      context: .
      dockerfile: docker/local/php/Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/src
      # https://www.php.net/downloads.php?os=windows
      - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/local/postgres/Dockerfile
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: study_laravel
      POSTGRES_PASSWORD: Passw0rd
    volumes:
      - db-data:/var/lib/postgresql
